### ISSUE TITLE
Non-human-readable playlists

### ISSUE THREAD

**Issue by katherinehackworth** [thisredone/beat-saber-playlist-maker#2]
Hey, what's the issue with playlists [that look like this?](https://user-images.githubusercontent.com/6628655/70869270-dcc48c00-1f4e-11ea-8930-b2a6075144ba.png) They're like that in a text editor too, so I doubt this is exclusive to this application, but what's up with that?

**Comment by thisredone** [comment]
This happens because the entries in a playlist only contain song hashes and not any other label. Most other software don't provide any other info than a hash when creating a playlist.
I can fix it though

**Comment by thisredone** [comment]
[Latest release](https://github.com/thisredone/beat-saber-playlist-maker/releases/latest) addresses it
